// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkqJyQL0Vsueb16IOPEgERublnuPfoQUA',
    appId: '1:1084958856293:web:0ce52e194c438f2c58228c',
    messagingSenderId: '1084958856293',
    projectId: 'anitocorn-firebase-auth-bloc',
    authDomain: 'anitocorn-firebase-auth-bloc.firebaseapp.com',
    storageBucket: 'anitocorn-firebase-auth-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9gNNbiflBaNdee5BUSWsdMu_2Vbe81wA',
    appId: '1:1084958856293:android:2aaf99340ffe213758228c',
    messagingSenderId: '1084958856293',
    projectId: 'anitocorn-firebase-auth-bloc',
    storageBucket: 'anitocorn-firebase-auth-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiXGpf1KjEhnkq2Z27vAJZcLc2_A9zmHI',
    appId: '1:1084958856293:ios:8f08965ae0ad68c758228c',
    messagingSenderId: '1084958856293',
    projectId: 'anitocorn-firebase-auth-bloc',
    storageBucket: 'anitocorn-firebase-auth-bloc.appspot.com',
    iosClientId: '1084958856293-hbr2m5nhfucdasu5kodql6mueiiirgdf.apps.googleusercontent.com',
    iosBundleId: 'com.anitocorn.anitocornFirebaseAuthBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiXGpf1KjEhnkq2Z27vAJZcLc2_A9zmHI',
    appId: '1:1084958856293:ios:8f08965ae0ad68c758228c',
    messagingSenderId: '1084958856293',
    projectId: 'anitocorn-firebase-auth-bloc',
    storageBucket: 'anitocorn-firebase-auth-bloc.appspot.com',
    iosClientId: '1084958856293-hbr2m5nhfucdasu5kodql6mueiiirgdf.apps.googleusercontent.com',
    iosBundleId: 'com.anitocorn.anitocornFirebaseAuthBloc',
  );
}
